// Display names for admin audit events and edited fields (data keys stay in the data layer's vocabulary).
export const ACTION_LABEL = {
  'user.profile.update': 'Ubah profil',
  'user.finance.update': 'Ubah keuangan',
  'application.transition': 'Ubah status pengajuan',
  'application.note': 'Catatan internal',
  'product.create': 'Buat draft produk',
  'product.update': 'Ubah produk',
  'product.publish': 'Terbitkan produk',
  'product.archive': 'Arsipkan produk',
  'bank.create': 'Tambah bank',
  'bank.update': 'Ubah bank',
  'article.create': 'Buat draft artikel',
  'article.update': 'Ubah artikel',
  'article.publish': 'Terbitkan artikel',
  'article.archive': 'Arsipkan artikel',
  'report.export': 'Unduh laporan CSV',
  'config.update': 'Ubah konfigurasi',
  'health.publish': 'Terbitkan formula KPR Health',
  'health.rollback': 'Pulihkan formula KPR Health',
}

export const FIELD_LABEL = {
  fullName: 'Nama',
  nik: 'NIK',
  birthPlace: 'Tempat lahir',
  birthDate: 'Tanggal lahir',
  gender: 'Jenis kelamin',
  maritalStatus: 'Status perkawinan',
  address: 'Alamat',
  phone: 'Nomor ponsel',
  email: 'Email',
  occupation: 'Pekerjaan',
  companyName: 'Perusahaan',
  jobTitle: 'Jabatan',
  workYears: 'Lama bekerja',
  workMonths: 'Tambahan bulan kerja',
  monthlyIncome: 'Penghasilan bulanan',
  jointIncome: 'Gabung penghasilan pasangan',
  partnerIncome: 'Penghasilan pasangan',
  vehicleDebt: 'Cicilan kendaraan',
  cardDebt: 'Kartu kredit / paylater',
  otherDebt: 'Pinjaman lain',
  note: 'Catatan',
  name: 'Nama',
  mark: 'Kode',
  active: 'Status aktif',
  bank: 'Bank',
  productTypes: 'Jenis',
  scheme: 'Skema',
  ratePeriods: 'Bunga',
  fees: 'Biaya',
  eligibility: 'Syarat',
  effectiveFrom: 'Berlaku dari',
  effectiveUntil: 'Berlaku sampai',
  lastVerifiedAt: 'Tanggal verifikasi',
  title: 'Judul',
  slug: 'Slug',
  tag: 'Tag',
  icon: 'Ikon',
  summary: 'Ringkasan',
  minutes: 'Menit baca',
  body: 'Isi',
  payment: 'Pengingat pembayaran',
  fixedExpiry: 'Pengingat masa fixed',
  channels: 'Kanal',
  maxFileMb: 'Ukuran maksimal',
  formats: 'Format file',
  from: 'Dari',
  to: 'Sampai',
  productType: 'Jenis produk',
  bankName: 'Bank',
  rows: 'Jumlah baris',
  status: 'Status',
  version: 'Versi',
}

export const PRODUCT_TYPES = [
  { value: 'primary', label: 'KPR Primary' },
  { value: 'takeover', label: 'Take Over' },
]

export const fieldList = (keys) => keys.map((k) => FIELD_LABEL[k] ?? k).join(', ')
